channels:
  - bioconda
  - conda-forge
  - defaults
  - hcc
dependencies:
  - snakemake-minimal =5.27.4
  - python =3.8
  - gatk4 =4.1.9.0
  - hisat2 =2.2.1
  - samtools =1.11
  - sra-tools
  - stringtie
  - biopython
  - git
  - fastp
  - numpy =1.19.4
  - biopython
  - bcbio-gff
  - pandas
  - unzip
  - gzip
  - wget
  - curl
  - dotnet-sdk =3.1.403
  - java-jdk =8.0.92
  - openssh
  - aspera-cli
  - r =4.0 # for ProteomeGenerator
  - bioconductor-biostrings # for ProteomeGenerator
  - picard # for ProteomeGenerator
  - transdecoder # for ProteomeGenerator
  - gffread # for ProteomeGenerator
  - blast # for ProteomeGenerdator

  # - mason # for generating reads for testing

  # - maven # for installing SnpEff; now downloading zip file directly

  # - rsem =1.3.2-0
  # - star =2.7.0f-0

  # - star-fusion =1.6.0 # for STAR-Fusion
  # - perl-carp-assert # for STAR-Fusion
  # - igv-reports # for STAR-Fusion
  # - trinity=2.8.4-0 # for STAR-Fusion
